# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

#version: 2
#updates:
#  - package-ecosystem: "terraform" # See documentation for possible values
#    directory: "/terraform/org-manager/tf-cost-alerts"
#    allow:
#      - dependency-name: "hashicorp/aws"
#      - dependency-name: "hashicorp/tfe"
#    commit-message:
#      prefix: "eng: (misc) "
#    groups:
#      terraform:
#        patterns:
#          - "*"
#        update-types:
#          - "minor"
#          - "patch"
#    schedule:
#      interval: "monthly"
#      time: "01:00"

version: 2
updates:
  - package-ecosystem: "terraform" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
